"""The commit-message check of ADR-0008, on the messages it must reject and must let through."""

from __future__ import annotations

from pathlib import Path

import pytest
from check_commit_message import find_attribution, main


@pytest.mark.parametrize(
    "line",
    [
        "Co-authored-by: Someone <someone@example.org>",
        "co-authored-by:someone",
        "  Co-Authored-By: A Tool <noreply@example.org>",
        "Generated with SomeTool",
        "This change was generated by an assistant",
        "Assistant-Session: 0123456789abcdef",
        "session-id: abc",
    ],
)
def test_attribution_is_rejected(line: str) -> None:
    """Each kind of attribution is found, whatever its case or spacing."""
    message = f"Add the layering test\n\nWhy it matters.\n\n{line}\n"
    assert find_attribution(message)


@pytest.mark.parametrize(
    "message",
    [
        "Add the layering test\n\nIt checks imports in both directions.\n",
        "Fix the session handling in the HTTP client\n",
        "Record which source generated each run\n",
        "Add tests\n\n# Co-authored-by: in a git comment never reaches the commit\n",
    ],
)
def test_ordinary_messages_pass(message: str) -> None:
    """Words like "session" or "generated" in prose are not attribution."""
    assert find_attribution(message) == []


def test_main_reports_and_fails(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    """The hook entry point exits non-zero and names the offending line."""
    clean = tmp_path / "clean.txt"
    clean.write_text("Add the scaffold\n", encoding="utf-8")
    dirty = tmp_path / "dirty.txt"
    dirty.write_text("Add the scaffold\n\nCo-authored-by: X <x@example.org>\n", encoding="utf-8")
    assert main([str(clean)]) == 0
    assert main([str(clean), str(dirty)]) == 1
    assert "line 3: co-author trailer" in capsys.readouterr().err


def test_main_without_arguments_is_a_usage_error() -> None:
    """No message file is a mistake in the hook wiring, not a clean message."""
    assert main([]) == 2
